// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace hyperhdrnet
{

public enum ImageType : byte
{
  NONE = 0,
  RawImage = 1,
  NV12Image = 2,
};



static public class ImageTypeVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((ImageType)typeId)
    {
      case ImageType.RawImage:
        result = hyperhdrnet.RawImageVerify.Verify(verifier, tablePos);
        break;
      case ImageType.NV12Image:
        result = hyperhdrnet.NV12ImageVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
